matrix:
  # allow_failures:
  #   - os: windows
  include:
    - os: osx
      language: node_js
      rust: 1.3.7
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - NODE_ENV=dev

    - os: linux
      language: node_js
      rust: 1.3.7
      services:
        - xvfb
      env:
        - NODE_ENV=dev
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-multilib
            - g++-8
            - g++-multilib
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso
            - rpm

    # - os: windows
    #   language: node_js
    #   rust: 1.3.7
    #   env:
    #     - ELECTRON_CACHE=$HOME/.cache/electron
    #     - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    #     - NODE_ENV=dev
    #     - YARN_GPG=no # otherwise this starts gpg-agent that never exits


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.rs
  - chmod +x ./rustup.rs
  - ./rustup.rs -y
  - source $HOME/.cargo/env
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs  | sh -y; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CXX="g++-8"; fi


install:
  - travis_wait 50 yarn --ignore-engines --network-timeout 800000;
  # On Linux, initialize "virtual display". See before_script


before_script:
  # osx set window size
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "/Library/Application Support/VMware Tools/vmware-resolutionSet" 1920 1080;
    fi
  # On Linux, create a "virtual display". This allows browsers to work properly
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi


script:
# update the xdg implementation on the machine. older version is buggy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp node_modules/open/xdg-open ~/bin/;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xdg-open --version;
    fi
  - yarn lint
  - travis_retry yarn run test-peruse --forceExit
  - travis_retry yarn run test-exts --forceExit
  - yarn package
  - travis_retry yarn test-e2e-packed ./__testcafe__/peruse.spec.ts
  - travis_retry yarn test-e2e-packed  ./__testcafe__/navigation.spec.ts
  - travis_retry yarn test-e2e-packed  ./__testcafe__/settingsMenu.spec.ts
  # TODO: reenable safe tests
  # - travis_retry yarn cafe-e2e-safe;



after_failure:
# - cat ~/.local/share/applications/mimeapps.list
- which xdg-open
- xdg-open --version
# - cat $TMPDIR/safe-browser.log;
# check resolution...
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  system_profiler SPDisplaysDataType | grep Resolution
  fi


before_deploy:

- yarn package
- NODE_ENV=prod yarn package
- cd release;
- |
  ls . | grep safe | while read RELEASE; do
  echo "deploying ${RELEASE} to GitHub releases as tagged with ${TRAVIS_TAG}";
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ditto -c -k --sequesterRsrc --keepParent ${RELEASE} ${RELEASE}.zip;
  fi
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r -q ${RELEASE}.zip ${RELEASE};
  fi
  done
# don't fail if nothing to do.
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -d *.zip *.DS_Store && zip -d *.zip  __MACOSX/\* || true;
  fi
- cd ..
- ls release
- export RELEASE_PROD_ZIP="$(ls release/*-x64.zip)";
- export RELEASE_DEV_ZIP="$(ls release/*-dev.zip)";
- echo "deploying ${RELEASE_PROD_ZIP} to GitHub releases as tagged with ${TRAVIS_TAG}"
- echo "deploying ${RELEASE_DEV_ZIP} to GitHub releases as tagged with ${TRAVIS_TAG}"
- ls release

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "${RELEASE_PROD_ZIP}"
    - "${RELEASE_DEV_ZIP}"
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
    branch: dev
