sudo: required
dist: trusty

os:
- osx
- linux
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- export NODE_ENV=production
script:
- yarn build
- yarn package
before_deploy:
- ls dist
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv dist/*.dmg dist/safe-browser-${TRAVIS_TAG}-osx-x64.dmg;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_PKG=$(ls dist/*.dmg);
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv dist/*.zip dist/safe-browser-${TRAVIS_TAG}-linux-x64.zip;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf dist/linux-unpacked;
  fi
- ls
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_PKG="$(ls dist/safe*)";
  fi
- echo "deploying ${RELEASE_PKG} to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dNUJgCh8UYnwLH09f7W3Wu/ZhO2wPBHkFlN8Z9n5uIXm1CH/FkZl6uqBZ1LTUov6K1kqhlDTpJvKd2lbQkYkbMcLqa5LN3vrXiJX0jmTmoIz4ujSpYcKeSfMSc8S7NBI4/w+hD6Z8d+3fUwNlQgZjrSQbkabpm/zmE7ShGGu9VjmrCXXGDWOxRBLWVP6ujzLTuLns2kC1gdtz7p7ceeZ5flXe24iSc4O8TZhUJkuC3vLvUuLiTfSoWAbtwNXZ1mjIj45M7cixTpsAyBmduEH6X/o2fCy8AuFuRTNHo24u0t1jie0OyVXqyDOVVQ+cIvzvgQCiyCljbx7ZxnOKum/PJ0QchkWSX6b9R14+EIPDiNDpshBrul+SKQDWlfKYkCpcQVsEIJrENuUpynrNZx8rQ41EF1d/uqpWAgBNG78MprqZ+9jZR+XSrz7zPn4/iBH3GZjtkwlRCm81exyF6jJypVyPkUFHh0npPRzoFdk6CR3ywk0EsSa6vWR04E2HzZBvBs5MOk2UHM5G7NUAsXLo3JGp1aLsBgU0+C2SIjmyvfielEKzUgmhLZFCItAada92QcEJU/6ekjGwL1uxVO7mqVth3iRatHS7Dk6x9t92rXNPihW7h0qGpA+Skg7PXTBP6QiIPOA4fAFzpG6GcDu4RWZnUPxBQluIvcnJdPwemw=
  file: "${RELEASE_PKG}"
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    all_branches: true
    tag: true
notifications:
  email:
    on_success:
    - change
    on_failure:
    - change
