platform:
  - x64

image: Visual Studio 2015

environment:
  nodejs_version: "8"
  matrix:
    - NODE_ENV: "prod"
      win_runtime: win-x64
      arch: x64
      plat: win32
    - NODE_ENV: "dev"
      win_runtime: win-x64
      arch: x64
      plat: win32

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - yarn --version
  - yarn config set child-concurrency 1
  - yarn
  - yarn add windows-build-tools --global


build_script:
  - node --version
  - yarn --version


before_deploy:
  - yarn run build
  - yarn run package
  - FOR /F %%i IN ('dir dist /b') DO SET APP_PKG_DIR=%%i
  - if [%NODE_ENV%]==[dev] (
      ren .\dist\%APP_PKG_DIR% mock-%APP_PKG_DIR%
    )
  - FOR /F %%G IN ('dir dist /b') DO SET APP_PKG_DIR=%%G
  - echo %APP_PKG_DIR%
  - for /f %%H in ('dir dist\%APP_PKG_DIR%  /b') do echo %%H
  - ps: >-
      If ($env:NODE_ENV -Match "prod") {
        $TOKEN="$env:GITHUB_ACCESS_TOKEN"
        $OWNER="MaidSafe"
        $REPO="release_config"
        $REPO_PATH="safe_authenticator/safe_browser.crust.config"
        $FILE="https://api.github.com/repos/$OWNER/$REPO/contents/$REPO_PATH"
        $APP_DIR="$env:APP_PKG_DIR"
        $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
        $headers.Add("Authorization", "token $TOKEN")
        $headers.Add("Accept", 'application/vnd.github.v3.raw')
        Invoke-WebRequest -URI $FILE -Headers $headers -OutFile ".\dist\$APP_DIR\safe-browser.crust.config"
      }
  - copy .\build\log.toml .\dist\%APP_PKG_DIR%\
  - ren .\dist\%APP_PKG_DIR%\"SAFE Browser.exe" safe-browser.exe
  - for /f %%H in ('dir dist\%APP_PKG_DIR%  /b') do echo %%H
  - cd dist
  - 7z a %APP_PKG_DIR%.zip
  - cd ..
  - for /f %%P in ('dir dist /b') do echo %%P
  - for /f %%P in ('dir .\dist\%APP_PKG_DIR%  /b') do echo %%P
  - certutil -hashfile .\dist\%APP_PKG_DIR%.zip SHA256 >> .\dist\%APP_PKG_DIR%.txt
  - echo %APPVEYOR_REPO_TAG%
  - echo %APPVEYOR_REPO_TAG_NAME%
  - ps: Get-ChildItem .\dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\dist\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }



deploy:
  release: $(appveyor_repo_tag_name)
  tag: $(appveyor_repo_tag_name)
  description: 'SAFE Browser'
  provider: GitHub
  auth_token: $(GITHUB_ACCESS_TOKEN)
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag:  true        # deploy on tag push only
