platform:
  - x64

image: Visual Studio 2017
os: unstable
environment:
  nodejs_version: "Stable"
  matrix:
    - NODE_ENV: "dev"
    - NODE_ENV: "production"
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
  - app\node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn --version
  - yarn add windows-build-tools --global
  - yarn --ignore-optional


build_script:
  - node --version
  - set NODE_ENV=production
  - yarn --version
  - yarn run build
  - yarn run package




after_build:
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - dir dist
  - cd dist
  - 7z a safe-browser-%APPVEYOR_REPO_TAG_NAME%-win-x64.zip
  - dir
  - echo %APPVEYOR_REPO_TAG%
  - echo %APPVEYOR_REPO_TAG_NAME%

artifacts:
  - path: dist/*

before_deploy:
    # - dir dist

deploy:
  release: $(appveyor_repo_tag_name)
  tag: $(appveyor_repo_tag_name)
  description: 'SAFE Browser'
  provider: GitHub
  auth_token:
    secure: yYDNGH+3V6HD/LemQHWRMtum9o98noPH8a02NFPJyuVKc+6vQWveTClb3+gRSnuB
 # your encrypted token from GitHub
  # artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: AddMockTravisBuild
    appveyor_repo_tag:  true        # deploy on tag push only
    # appveyor_repo_tag:  true        # deploy on tag push only
